import { chromium } from "@playwright/test";
const B = "http://localhost:3000";
const b = await chromium.launch();
const p = await b.newContext({ viewport: { width: 1440, height: 1400 }, locale: "de-DE" }).then((c) => c.newPage());
p.setDefaultTimeout(60000);
p.on("console", (m) => { if (m.type() === "error") console.log("BROWSER:", m.text().slice(0, 200)); });
await p.goto(`${B}/register`, { waitUntil: "domcontentloaded" });
const e = `dbg-${Date.now()}@example.invalid`;
await p.getByLabel("E-Mail-Adresse").fill(e);
await p.getByLabel("Passwort", { exact: false }).first().fill("ProbeProbe1234!");
await p.getByRole("button", { name: /Konto anlegen/i }).click();
await p.waitForURL(/\/(app|setup)/, { timeout: 60000 });
await p.goto(`${B}/business`, { waitUntil: "domcontentloaded" });
await p.waitForTimeout(2000);
await p.getByLabel("Name des Unternehmens").fill("Debug GmbH");
await p.getByRole("button", { name: /^Anlegen$/ }).click();
await p.waitForTimeout(3000);
await p.goto(`${B}/business/stellen`, { waitUntil: "domcontentloaded" });
await p.waitForTimeout(1500);
await p.getByRole("button", { name: /Neue Stelle/ }).click();
await p.getByLabel("Titel der Stelle").fill("Test (m/w/d)");
await p.getByRole("button", { name: /^Anlegen$/ }).click();
await p.waitForURL(/\/business\/stellen\/[0-9a-f-]{36}/, { timeout: 60000 });
await p.getByLabel("Ort", { exact: true }).fill("Dortmund");
await p.getByLabel("Beschreibung").fill("x".repeat(200));
console.log("Knöpfe:", await p.getByRole("button").allInnerTexts());
await p.getByRole("button", { name: /^Speichern$/ }).click();
await p.waitForTimeout(5000);
const t = (await p.locator("body").innerText()).replace(/\s+/g, " ");
console.log("Status danach:", /Gespeichert/.test(t) ? "Gespeichert gefunden" : t.slice(-300));
await b.close();
