import { chromium } from "@playwright/test";
const B = "http://localhost:3000";
const b = await chromium.launch();
const p = await b.newContext({ viewport: { width: 1440, height: 1000 }, locale: "de-DE" }).then((c) => c.newPage());
p.setDefaultTimeout(60000);
p.on("framenavigated", (f) => { if (f === p.mainFrame()) console.log("NAV:", f.url()); });
await p.goto(`${B}/register`, { waitUntil: "domcontentloaded" });
await p.getByLabel("E-Mail-Adresse").fill(`dbg4-${Date.now()}@example.invalid`);
await p.getByLabel("Passwort", { exact: false }).first().fill("ProbeProbe1234!");
await p.getByRole("button", { name: /Konto anlegen/i }).click();
await p.waitForURL(/\/(app|setup)/, { timeout: 60000 });
await p.goto(`${B}/app/jobs`, { waitUntil: "domcontentloaded" });
await p.waitForTimeout(3000);
console.log("--- Eingabe ---");
const f = p.getByRole("searchbox").first();
await f.fill("Nur Stellen ab 45.000 €");
await f.press("Enter");
await p.waitForTimeout(4000);
console.log("URL:", p.url());
console.log("Chips:", JSON.stringify(await p.locator('ul[aria-label="Aktive Filter"] button').allInnerTexts()));
await b.close();
process.exit(0);
