import { chromium } from "@playwright/test";
const B = "http://localhost:3000";
const b = await chromium.launch();
const s = await b.newPage({ baseURL: B });
const fehler = [];
s.on("console", m => { if (m.type()==="error") fehler.push(m.text()); });
await s.goto(`${B}/register`);
await s.getByLabel("E-Mail-Adresse").fill(`e2e-fuss-${Date.now()}@example.invalid`);
await s.getByLabel("Passwort", { exact: false }).first().fill("ProbeProbe1234!");
await s.getByRole("button", { name: /Konto anlegen/i }).click();
await s.waitForURL(/\/(app|setup)/, { timeout: 45000 });
await s.goto(`${B}/app/jobs`, { waitUntil: "domcontentloaded" });
await s.waitForTimeout(3000);
const kacheln = await s.locator('a[href^="/jobs?land="]').count();
console.log("Länderkacheln im Fuss:", kacheln);
const bilder = await s.locator('img[src*="/flaggen/"]').count();
console.log("Flaggenbilder:", bilder);
const erste = await s.locator('a[href^="/jobs?land="]').first().innerText().catch(()=>"-");
console.log("Erste Kachel:", erste.replace(/\n/g," "));
const kaputt = await s.evaluate(() => [...document.images].filter(i=>i.complete && i.naturalWidth===0).map(i=>i.src));
console.log("Kaputte Bilder:", kaputt.length, kaputt.slice(0,3));
console.log("Konsolenfehler:", fehler.length, fehler.slice(0,2));
await b.close();
