import { chromium } from "@playwright/test";
const B = "http://localhost:3000";
const b = await chromium.launch();
const p = await b.newContext({ viewport: { width: 1440, height: 1100 }, locale: "de-DE" }).then((c) => c.newPage());
p.setDefaultTimeout(90000);
await p.goto(`${B}/register`, { waitUntil: "domcontentloaded" });
const k = `ist-${Date.now()}@example.invalid`;
await p.getByLabel("E-Mail-Adresse").fill(k);
await p.getByLabel("Passwort", { exact: false }).first().fill("ProbeProbe1234!");
await p.getByRole("button", { name: /Konto anlegen/i }).click();
await p.waitForURL(/\/(app|setup)/, { timeout: 60000 });
console.log("Konto:", k);
await p.goto(`${B}/app/jobs`, { waitUntil: "domcontentloaded" });
await p.waitForTimeout(4000);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-timenseling-eupoc-website/4822fabd-7824-4564-8475-fbcf29046710/scratchpad/ist-jobs.png" });
const t = (await p.locator("main").innerText()).replace(/\s+/g," ");
console.log("--- Jobliste, erste 1200 Zeichen ---");
console.log(t.slice(0, 1200));
await b.close();
