import { chromium } from "@playwright/test";
const B = "http://localhost:3000";
const b = await chromium.launch();
const s = await b.newPage({ baseURL: B, viewport: { width: 1280, height: 900 } });
await s.goto(`${B}/register`);
await s.getByLabel("E-Mail-Adresse").fill(`e2e-pb2-${Date.now()}@example.invalid`);
await s.getByLabel("Passwort", { exact: false }).first().fill("ProbeProbe1234!");
await s.getByRole("button", { name: /Konto anlegen/i }).click();
await s.waitForURL(/\/(app|setup)/, { timeout: 60000 });
await s.goto(`${B}/app/settings`, { waitUntil: "domcontentloaded", timeout: 180000 });
await s.waitForTimeout(2500);
await s.setInputFiles('input[type="file"][name="bild"]', "apps/web/public/flaggen/de.webp");
await s.getByRole("button", { name: /Hochladen|Ersetzen/ }).click();
await s.waitForTimeout(4000);
console.log("direkt nach dem Hochladen:", await s.locator('img[src="/app/profilbild"]').count());
await s.reload({ waitUntil: "domcontentloaded" });
await s.waitForTimeout(3000);
console.log("nach dem Neuladen:      ", await s.locator('img[src="/app/profilbild"]').count());
const antwort = await s.request.get(`${B}/app/profilbild`);
console.log("Route liefert:", antwort.status(), antwort.headers()["content-type"]);
await b.close();
