import { chromium } from "@playwright/test";
const B = "http://localhost:3000";
const b = await chromium.launch();
const s = await b.newPage({ baseURL: B, viewport: { width: 1440, height: 900 } });
await s.goto(`${B}/register`);
await s.getByLabel("E-Mail-Adresse").fill(`e2e-str-${Date.now()}@example.invalid`);
await s.getByLabel("Passwort", { exact: false }).first().fill("ProbeProbe1234!");
await s.getByRole("button", { name: /Konto anlegen/i }).click();
await s.waitForURL(/\/(app|setup)/, { timeout: 60000 });
await s.goto(`${B}/app/jobs`, { waitUntil: "domcontentloaded", timeout: 120000 });
await s.waitForTimeout(2000);
await s.mouse.move(600, 400); await s.mouse.wheel(0, 120); await s.waitForTimeout(7000);
await s.mouse.wheel(0, -200); await s.waitForTimeout(800);
await s.screenshot({ path: "/tmp/kopf-oben-light.png", clip: { x: 0, y: 0, width: 1440, height: 250 } });
await s.evaluate(() => document.documentElement.setAttribute("data-theme","dark"));
await s.waitForTimeout(900);
await s.screenshot({ path: "/tmp/kopf-oben-dark.png", clip: { x: 0, y: 0, width: 1440, height: 250 } });
console.log("Bilder erzeugt");
await b.close();
